// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: services/orion-baremetal/proto/v1/baremetal.proto

package baremetalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PowerState int32

const (
	PowerState_POWER_STATE_UNKNOWN PowerState = 0
	PowerState_POWER_STATE_ON      PowerState = 1
	PowerState_POWER_STATE_OFF     PowerState = 2
	PowerState_POWER_STATE_REBOOT  PowerState = 3
)

// Enum value maps for PowerState.
var (
	PowerState_name = map[int32]string{
		0: "POWER_STATE_UNKNOWN",
		1: "POWER_STATE_ON",
		2: "POWER_STATE_OFF",
		3: "POWER_STATE_REBOOT",
	}
	PowerState_value = map[string]int32{
		"POWER_STATE_UNKNOWN": 0,
		"POWER_STATE_ON":      1,
		"POWER_STATE_OFF":     2,
		"POWER_STATE_REBOOT":  3,
	}
)

func (x PowerState) Enum() *PowerState {
	p := new(PowerState)
	*p = x
	return p
}

func (x PowerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerState) Descriptor() protoreflect.EnumDescriptor {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_enumTypes[0].Descriptor()
}

func (PowerState) Type() protoreflect.EnumType {
	return &file_services_orion_baremetal_proto_v1_baremetal_proto_enumTypes[0]
}

func (x PowerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerState.Descriptor instead.
func (PowerState) EnumDescriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{0}
}

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNKNOWN   NodeStatus = 0
	NodeStatus_NODE_STATUS_ENROLLING NodeStatus = 1
	NodeStatus_NODE_STATUS_ACTIVE    NodeStatus = 2
	NodeStatus_NODE_STATUS_DEGRADED  NodeStatus = 3
	NodeStatus_NODE_STATUS_FAILED    NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNKNOWN",
		1: "NODE_STATUS_ENROLLING",
		2: "NODE_STATUS_ACTIVE",
		3: "NODE_STATUS_DEGRADED",
		4: "NODE_STATUS_FAILED",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNKNOWN":   0,
		"NODE_STATUS_ENROLLING": 1,
		"NODE_STATUS_ACTIVE":    2,
		"NODE_STATUS_DEGRADED":  3,
		"NODE_STATUS_FAILED":    4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_services_orion_baremetal_proto_v1_baremetal_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{1}
}

type BaremetalNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`
	PowerState    PowerState             `protobuf:"varint,4,opt,name=power_state,json=powerState,proto3,enum=baremetal.v1.PowerState" json:"power_state,omitempty"`
	BootDevice    string                 `protobuf:"bytes,5,opt,name=boot_device,json=bootDevice,proto3" json:"boot_device,omitempty"`
	SecurityMode  string                 `protobuf:"bytes,6,opt,name=security_mode,json=securityMode,proto3" json:"security_mode,omitempty"`
	Status        NodeStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=baremetal.v1.NodeStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaremetalNode) Reset() {
	*x = BaremetalNode{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaremetalNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaremetalNode) ProtoMessage() {}

func (x *BaremetalNode) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaremetalNode.ProtoReflect.Descriptor instead.
func (*BaremetalNode) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{0}
}

func (x *BaremetalNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaremetalNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaremetalNode) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *BaremetalNode) GetPowerState() PowerState {
	if x != nil {
		return x.PowerState
	}
	return PowerState_POWER_STATE_UNKNOWN
}

func (x *BaremetalNode) GetBootDevice() string {
	if x != nil {
		return x.BootDevice
	}
	return ""
}

func (x *BaremetalNode) GetSecurityMode() string {
	if x != nil {
		return x.SecurityMode
	}
	return ""
}

func (x *BaremetalNode) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNKNOWN
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BootDevice    string                 `protobuf:"bytes,5,opt,name=boot_device,json=bootDevice,proto3" json:"boot_device,omitempty"`
	SecurityMode  string                 `protobuf:"bytes,6,opt,name=security_mode,json=securityMode,proto3" json:"security_mode,omitempty"`
	Config        map[string]string      `protobuf:"bytes,7,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *CreateNodeRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CreateNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateNodeRequest) GetBootDevice() string {
	if x != nil {
		return x.BootDevice
	}
	return ""
}

func (x *CreateNodeRequest) GetSecurityMode() string {
	if x != nil {
		return x.SecurityMode
	}
	return ""
}

func (x *CreateNodeRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *BaremetalNode         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeResponse) Reset() {
	*x = CreateNodeResponse{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeResponse) ProtoMessage() {}

func (x *CreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNodeResponse) GetNode() *BaremetalNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *BaremetalNode         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeResponse) GetNode() *BaremetalNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{5}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*BaremetalNode       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesResponse) GetNodes() []*BaremetalNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SetPowerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PowerState    PowerState             `protobuf:"varint,2,opt,name=power_state,json=powerState,proto3,enum=baremetal.v1.PowerState" json:"power_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPowerStateRequest) Reset() {
	*x = SetPowerStateRequest{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPowerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPowerStateRequest) ProtoMessage() {}

func (x *SetPowerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPowerStateRequest.ProtoReflect.Descriptor instead.
func (*SetPowerStateRequest) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{7}
}

func (x *SetPowerStateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetPowerStateRequest) GetPowerState() PowerState {
	if x != nil {
		return x.PowerState
	}
	return PowerState_POWER_STATE_UNKNOWN
}

type SetBootDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BootDevice    string                 `protobuf:"bytes,2,opt,name=boot_device,json=bootDevice,proto3" json:"boot_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootDeviceRequest) Reset() {
	*x = SetBootDeviceRequest{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootDeviceRequest) ProtoMessage() {}

func (x *SetBootDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootDeviceRequest.ProtoReflect.Descriptor instead.
func (*SetBootDeviceRequest) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{8}
}

func (x *SetBootDeviceRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetBootDeviceRequest) GetBootDevice() string {
	if x != nil {
		return x.BootDevice
	}
	return ""
}

type ProvisionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InstanceInfo  string                 `protobuf:"bytes,2,opt,name=instance_info,json=instanceInfo,proto3" json:"instance_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionNodeRequest) Reset() {
	*x = ProvisionNodeRequest{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionNodeRequest) ProtoMessage() {}

func (x *ProvisionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionNodeRequest.ProtoReflect.Descriptor instead.
func (*ProvisionNodeRequest) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{9}
}

func (x *ProvisionNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ProvisionNodeRequest) GetInstanceInfo() string {
	if x != nil {
		return x.InstanceInfo
	}
	return ""
}

type DeprovisionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprovisionNodeRequest) Reset() {
	*x = DeprovisionNodeRequest{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprovisionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprovisionNodeRequest) ProtoMessage() {}

func (x *DeprovisionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprovisionNodeRequest.ProtoReflect.Descriptor instead.
func (*DeprovisionNodeRequest) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{10}
}

func (x *DeprovisionNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP(), []int{11}
}

func (x *OperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_services_orion_baremetal_proto_v1_baremetal_proto protoreflect.FileDescriptor

const file_services_orion_baremetal_proto_v1_baremetal_proto_rawDesc = "" +
	"\n" +
	"1services/orion-baremetal/proto/v1/baremetal.proto\x12\fbaremetal.v1\"\xfe\x01\n" +
	"\rBaremetalNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x03 \x01(\tR\x06driver\x129\n" +
	"\vpower_state\x18\x04 \x01(\x0e2\x18.baremetal.v1.PowerStateR\n" +
	"powerState\x12\x1f\n" +
	"\vboot_device\x18\x05 \x01(\tR\n" +
	"bootDevice\x12#\n" +
	"\rsecurity_mode\x18\x06 \x01(\tR\fsecurityMode\x120\n" +
	"\x06status\x18\a \x01(\x0e2\x18.baremetal.v1.NodeStatusR\x06status\"\xba\x02\n" +
	"\x11CreateNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vboot_device\x18\x05 \x01(\tR\n" +
	"bootDevice\x12#\n" +
	"\rsecurity_mode\x18\x06 \x01(\tR\fsecurityMode\x12C\n" +
	"\x06config\x18\a \x03(\v2+.baremetal.v1.CreateNodeRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x12CreateNodeResponse\x12/\n" +
	"\x04node\x18\x01 \x01(\v2\x1b.baremetal.v1.BaremetalNodeR\x04node\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"B\n" +
	"\x0fGetNodeResponse\x12/\n" +
	"\x04node\x18\x01 \x01(\v2\x1b.baremetal.v1.BaremetalNodeR\x04node\"\x12\n" +
	"\x10ListNodesRequest\"F\n" +
	"\x11ListNodesResponse\x121\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1b.baremetal.v1.BaremetalNodeR\x05nodes\"j\n" +
	"\x14SetPowerStateRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\vpower_state\x18\x02 \x01(\x0e2\x18.baremetal.v1.PowerStateR\n" +
	"powerState\"P\n" +
	"\x14SetBootDeviceRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vboot_device\x18\x02 \x01(\tR\n" +
	"bootDevice\"T\n" +
	"\x14ProvisionNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rinstance_info\x18\x02 \x01(\tR\finstanceInfo\"1\n" +
	"\x16DeprovisionNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"f\n" +
	"\x11OperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*f\n" +
	"\n" +
	"PowerState\x12\x17\n" +
	"\x13POWER_STATE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0ePOWER_STATE_ON\x10\x01\x12\x13\n" +
	"\x0fPOWER_STATE_OFF\x10\x02\x12\x16\n" +
	"\x12POWER_STATE_REBOOT\x10\x03*\x8a\x01\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\x13NODE_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15NODE_STATUS_ENROLLING\x10\x01\x12\x16\n" +
	"\x12NODE_STATUS_ACTIVE\x10\x02\x12\x18\n" +
	"\x14NODE_STATUS_DEGRADED\x10\x03\x12\x16\n" +
	"\x12NODE_STATUS_FAILED\x10\x042\xd5\x04\n" +
	"\x10BaremetalService\x12O\n" +
	"\n" +
	"CreateNode\x12\x1f.baremetal.v1.CreateNodeRequest\x1a .baremetal.v1.CreateNodeResponse\x12F\n" +
	"\aGetNode\x12\x1c.baremetal.v1.GetNodeRequest\x1a\x1d.baremetal.v1.GetNodeResponse\x12L\n" +
	"\tListNodes\x12\x1e.baremetal.v1.ListNodesRequest\x1a\x1f.baremetal.v1.ListNodesResponse\x12T\n" +
	"\rSetPowerState\x12\".baremetal.v1.SetPowerStateRequest\x1a\x1f.baremetal.v1.OperationResponse\x12T\n" +
	"\rSetBootDevice\x12\".baremetal.v1.SetBootDeviceRequest\x1a\x1f.baremetal.v1.OperationResponse\x12T\n" +
	"\rProvisionNode\x12\".baremetal.v1.ProvisionNodeRequest\x1a\x1f.baremetal.v1.OperationResponse\x12X\n" +
	"\x0fDeprovisionNode\x12$.baremetal.v1.DeprovisionNodeRequest\x1a\x1f.baremetal.v1.OperationResponseBHZFgithub.com/horizon/orion/services/orion-baremetal/proto/v1;baremetalv1b\x06proto3"

var (
	file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescOnce sync.Once
	file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescData []byte
)

func file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescGZIP() []byte {
	file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescOnce.Do(func() {
		file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_orion_baremetal_proto_v1_baremetal_proto_rawDesc), len(file_services_orion_baremetal_proto_v1_baremetal_proto_rawDesc)))
	})
	return file_services_orion_baremetal_proto_v1_baremetal_proto_rawDescData
}

var file_services_orion_baremetal_proto_v1_baremetal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_services_orion_baremetal_proto_v1_baremetal_proto_goTypes = []any{
	(PowerState)(0),                // 0: baremetal.v1.PowerState
	(NodeStatus)(0),                // 1: baremetal.v1.NodeStatus
	(*BaremetalNode)(nil),          // 2: baremetal.v1.BaremetalNode
	(*CreateNodeRequest)(nil),      // 3: baremetal.v1.CreateNodeRequest
	(*CreateNodeResponse)(nil),     // 4: baremetal.v1.CreateNodeResponse
	(*GetNodeRequest)(nil),         // 5: baremetal.v1.GetNodeRequest
	(*GetNodeResponse)(nil),        // 6: baremetal.v1.GetNodeResponse
	(*ListNodesRequest)(nil),       // 7: baremetal.v1.ListNodesRequest
	(*ListNodesResponse)(nil),      // 8: baremetal.v1.ListNodesResponse
	(*SetPowerStateRequest)(nil),   // 9: baremetal.v1.SetPowerStateRequest
	(*SetBootDeviceRequest)(nil),   // 10: baremetal.v1.SetBootDeviceRequest
	(*ProvisionNodeRequest)(nil),   // 11: baremetal.v1.ProvisionNodeRequest
	(*DeprovisionNodeRequest)(nil), // 12: baremetal.v1.DeprovisionNodeRequest
	(*OperationResponse)(nil),      // 13: baremetal.v1.OperationResponse
	nil,                            // 14: baremetal.v1.CreateNodeRequest.ConfigEntry
}
var file_services_orion_baremetal_proto_v1_baremetal_proto_depIdxs = []int32{
	0,  // 0: baremetal.v1.BaremetalNode.power_state:type_name -> baremetal.v1.PowerState
	1,  // 1: baremetal.v1.BaremetalNode.status:type_name -> baremetal.v1.NodeStatus
	14, // 2: baremetal.v1.CreateNodeRequest.config:type_name -> baremetal.v1.CreateNodeRequest.ConfigEntry
	2,  // 3: baremetal.v1.CreateNodeResponse.node:type_name -> baremetal.v1.BaremetalNode
	2,  // 4: baremetal.v1.GetNodeResponse.node:type_name -> baremetal.v1.BaremetalNode
	2,  // 5: baremetal.v1.ListNodesResponse.nodes:type_name -> baremetal.v1.BaremetalNode
	0,  // 6: baremetal.v1.SetPowerStateRequest.power_state:type_name -> baremetal.v1.PowerState
	3,  // 7: baremetal.v1.BaremetalService.CreateNode:input_type -> baremetal.v1.CreateNodeRequest
	5,  // 8: baremetal.v1.BaremetalService.GetNode:input_type -> baremetal.v1.GetNodeRequest
	7,  // 9: baremetal.v1.BaremetalService.ListNodes:input_type -> baremetal.v1.ListNodesRequest
	9,  // 10: baremetal.v1.BaremetalService.SetPowerState:input_type -> baremetal.v1.SetPowerStateRequest
	10, // 11: baremetal.v1.BaremetalService.SetBootDevice:input_type -> baremetal.v1.SetBootDeviceRequest
	11, // 12: baremetal.v1.BaremetalService.ProvisionNode:input_type -> baremetal.v1.ProvisionNodeRequest
	12, // 13: baremetal.v1.BaremetalService.DeprovisionNode:input_type -> baremetal.v1.DeprovisionNodeRequest
	4,  // 14: baremetal.v1.BaremetalService.CreateNode:output_type -> baremetal.v1.CreateNodeResponse
	6,  // 15: baremetal.v1.BaremetalService.GetNode:output_type -> baremetal.v1.GetNodeResponse
	8,  // 16: baremetal.v1.BaremetalService.ListNodes:output_type -> baremetal.v1.ListNodesResponse
	13, // 17: baremetal.v1.BaremetalService.SetPowerState:output_type -> baremetal.v1.OperationResponse
	13, // 18: baremetal.v1.BaremetalService.SetBootDevice:output_type -> baremetal.v1.OperationResponse
	13, // 19: baremetal.v1.BaremetalService.ProvisionNode:output_type -> baremetal.v1.OperationResponse
	13, // 20: baremetal.v1.BaremetalService.DeprovisionNode:output_type -> baremetal.v1.OperationResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_services_orion_baremetal_proto_v1_baremetal_proto_init() }
func file_services_orion_baremetal_proto_v1_baremetal_proto_init() {
	if File_services_orion_baremetal_proto_v1_baremetal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_orion_baremetal_proto_v1_baremetal_proto_rawDesc), len(file_services_orion_baremetal_proto_v1_baremetal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_orion_baremetal_proto_v1_baremetal_proto_goTypes,
		DependencyIndexes: file_services_orion_baremetal_proto_v1_baremetal_proto_depIdxs,
		EnumInfos:         file_services_orion_baremetal_proto_v1_baremetal_proto_enumTypes,
		MessageInfos:      file_services_orion_baremetal_proto_v1_baremetal_proto_msgTypes,
	}.Build()
	File_services_orion_baremetal_proto_v1_baremetal_proto = out.File
	file_services_orion_baremetal_proto_v1_baremetal_proto_goTypes = nil
	file_services_orion_baremetal_proto_v1_baremetal_proto_depIdxs = nil
}
