// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: services/orion-baremetal/proto/v1/baremetal.proto

package baremetalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaremetalService_CreateNode_FullMethodName      = "/baremetal.v1.BaremetalService/CreateNode"
	BaremetalService_GetNode_FullMethodName         = "/baremetal.v1.BaremetalService/GetNode"
	BaremetalService_ListNodes_FullMethodName       = "/baremetal.v1.BaremetalService/ListNodes"
	BaremetalService_SetPowerState_FullMethodName   = "/baremetal.v1.BaremetalService/SetPowerState"
	BaremetalService_SetBootDevice_FullMethodName   = "/baremetal.v1.BaremetalService/SetBootDevice"
	BaremetalService_ProvisionNode_FullMethodName   = "/baremetal.v1.BaremetalService/ProvisionNode"
	BaremetalService_DeprovisionNode_FullMethodName = "/baremetal.v1.BaremetalService/DeprovisionNode"
)

// BaremetalServiceClient is the client API for BaremetalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaremetalServiceClient interface {
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	SetPowerState(ctx context.Context, in *SetPowerStateRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	SetBootDevice(ctx context.Context, in *SetBootDeviceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	ProvisionNode(ctx context.Context, in *ProvisionNodeRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	DeprovisionNode(ctx context.Context, in *DeprovisionNodeRequest, opts ...grpc.CallOption) (*OperationResponse, error)
}

type baremetalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaremetalServiceClient(cc grpc.ClientConnInterface) BaremetalServiceClient {
	return &baremetalServiceClient{cc}
}

func (c *baremetalServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNodeResponse)
	err := c.cc.Invoke(ctx, BaremetalService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baremetalServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, BaremetalService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baremetalServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, BaremetalService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baremetalServiceClient) SetPowerState(ctx context.Context, in *SetPowerStateRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, BaremetalService_SetPowerState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baremetalServiceClient) SetBootDevice(ctx context.Context, in *SetBootDeviceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, BaremetalService_SetBootDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baremetalServiceClient) ProvisionNode(ctx context.Context, in *ProvisionNodeRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, BaremetalService_ProvisionNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baremetalServiceClient) DeprovisionNode(ctx context.Context, in *DeprovisionNodeRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, BaremetalService_DeprovisionNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaremetalServiceServer is the server API for BaremetalService service.
// All implementations must embed UnimplementedBaremetalServiceServer
// for forward compatibility.
type BaremetalServiceServer interface {
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	SetPowerState(context.Context, *SetPowerStateRequest) (*OperationResponse, error)
	SetBootDevice(context.Context, *SetBootDeviceRequest) (*OperationResponse, error)
	ProvisionNode(context.Context, *ProvisionNodeRequest) (*OperationResponse, error)
	DeprovisionNode(context.Context, *DeprovisionNodeRequest) (*OperationResponse, error)
	mustEmbedUnimplementedBaremetalServiceServer()
}

// UnimplementedBaremetalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaremetalServiceServer struct{}

func (UnimplementedBaremetalServiceServer) CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedBaremetalServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedBaremetalServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedBaremetalServiceServer) SetPowerState(context.Context, *SetPowerStateRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPowerState not implemented")
}
func (UnimplementedBaremetalServiceServer) SetBootDevice(context.Context, *SetBootDeviceRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBootDevice not implemented")
}
func (UnimplementedBaremetalServiceServer) ProvisionNode(context.Context, *ProvisionNodeRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionNode not implemented")
}
func (UnimplementedBaremetalServiceServer) DeprovisionNode(context.Context, *DeprovisionNodeRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeprovisionNode not implemented")
}
func (UnimplementedBaremetalServiceServer) mustEmbedUnimplementedBaremetalServiceServer() {}
func (UnimplementedBaremetalServiceServer) testEmbeddedByValue()                          {}

// UnsafeBaremetalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaremetalServiceServer will
// result in compilation errors.
type UnsafeBaremetalServiceServer interface {
	mustEmbedUnimplementedBaremetalServiceServer()
}

func RegisterBaremetalServiceServer(s grpc.ServiceRegistrar, srv BaremetalServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaremetalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaremetalService_ServiceDesc, srv)
}

func _BaremetalService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaremetalServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaremetalService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaremetalServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaremetalService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaremetalServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaremetalService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaremetalServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaremetalService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaremetalServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaremetalService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaremetalServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaremetalService_SetPowerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPowerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaremetalServiceServer).SetPowerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaremetalService_SetPowerState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaremetalServiceServer).SetPowerState(ctx, req.(*SetPowerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaremetalService_SetBootDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBootDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaremetalServiceServer).SetBootDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaremetalService_SetBootDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaremetalServiceServer).SetBootDevice(ctx, req.(*SetBootDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaremetalService_ProvisionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaremetalServiceServer).ProvisionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaremetalService_ProvisionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaremetalServiceServer).ProvisionNode(ctx, req.(*ProvisionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaremetalService_DeprovisionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeprovisionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaremetalServiceServer).DeprovisionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaremetalService_DeprovisionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaremetalServiceServer).DeprovisionNode(ctx, req.(*DeprovisionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaremetalService_ServiceDesc is the grpc.ServiceDesc for BaremetalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaremetalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baremetal.v1.BaremetalService",
	HandlerType: (*BaremetalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _BaremetalService_CreateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _BaremetalService_GetNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _BaremetalService_ListNodes_Handler,
		},
		{
			MethodName: "SetPowerState",
			Handler:    _BaremetalService_SetPowerState_Handler,
		},
		{
			MethodName: "SetBootDevice",
			Handler:    _BaremetalService_SetBootDevice_Handler,
		},
		{
			MethodName: "ProvisionNode",
			Handler:    _BaremetalService_ProvisionNode_Handler,
		},
		{
			MethodName: "DeprovisionNode",
			Handler:    _BaremetalService_DeprovisionNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/orion-baremetal/proto/v1/baremetal.proto",
}
